feat: [BREAKING] remove adapter from Action class
dialectlabs/blinks pull request #32
Opened 2024-10-18 13:08 UTC by fsher

2024-10-18 16:36 UTC, prsvic approved these changes
Like👍

2024-10-18 17:47 UTC, tsmbl requested changes

2024-10-18 17:47 UTC, tsmbl commented on packages/blinks-core/src/api/Action/action-supportability.ts
> +  adapter?: ActionAdapter,
I think we changing the behaviour when keep it optional here

Can you please doublecheck that e.g. monad blink shows incompatible fallback? 

solana-action:https://test-action-inputs.dialect.workers.dev/monad-poc/transfer

2024-10-18 17:48 UTC, fsher commented on packages/blinks-core/src/api/Action/action-supportability.ts
> +  adapter?: ActionAdapter,
will test, thank you!

2024-10-23 09:51 UTC, tsmbl approved these changes
Lgtm

2024-10-23 09:59 UTC, merged