Updated the blinks image aspect ratio to auto
dialectlabs/blinks pull request #8
Opened 2024-07-16 07:43 UTC by irffanasiff

The aspect ratio of the rendered image is always squared which is causing issue for a lot of devs who already have og images on their links for websites which are mostly 16:9 or maybe 4:3 aspect ratio
example here
<img width="887" alt="Screenshot 2024-07-16 at 1 12 35 PM" src="https://github.com/user-attachments/assets/6581e0b4-37e8-429e-940b-8024b20e5d2d">

it is better to give option to render with the aspect ratio which users choose most of them will have either 1:1 or 16:9 ( because this is the default og image ratio for twitter previews )

2024-07-16 13:42 UTC, zhelezkov requested changes
Hey, thanks for PR!

I did some tests, and it works fine, however there's some weird edge cases that might lead to bad experience if image configured incorrectly. For example since blinks are limited by it's height, it could lead to enormously long images.
Please see screenshot attached
<img width="658" alt="Screenshot 2024-07-16 at 16 35 47" src="https://github.com/user-attachments/assets/9d0d6042-1539-4c7a-80fa-1293d9ade6bd">

My recommendation is to make sure that min aspect ration for images is 16/9 and maximum is 1/1, do you think you can address it to cover edge case?

Thanks!

2024-07-17 01:36 UTC, WaggMe commented
> Hey, thanks for PR!
> 
> I did some tests, and it works fine, however there's some weird edge cases that might lead to bad experience if image configured incorrectly. For example since blinks are limited by it's height, it could lead to enormously long images. Please see screenshot attached <img alt="Screenshot 2024-07-16 at 16 35 47" width="658" src="https://private-user-images.githubusercontent.com/5163918/349105728-9d0d6042-1539-4c7a-80fa-1293d9ade6bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzk1NzcsIm5iZiI6MTcyMTE3OTI3NywicGF0aCI6Ii81MTYzOTE4LzM0OTEwNTcyOC05ZDBkNjA0Mi0xNTM5LTRjN2EtODBmYS0xMjkzZDlhZGU2YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMDEyMTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc2NmZiMTg3OTc1Njg3ZTc3ODZlNzM2ZjhhNTZlYWNiZjAwMGE2ZDU5ZTRiZDUyYTljMWIwNjczZjAxYzAwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HBptDLJFIT-B5z_vzd8jw_WehOmQIDMeMyfBvESyZk4">
> 
> My recommendation is to make sure that min aspect ration for images is 16/9 and maximum is 1/1, do you think you can address it to cover edge case?
> 
> Thanks!

Adding some context from discussions I've had with other developers about blinks, there is definitely demand for a wide range of image aspect ratios.

**(width : height ratios)**
* 10:1 or 5:1 - Useful for micro-banners on blinks that are intended to take up less vertical space, such as embeds in other websites or apps, widget-style interactions, and for streamlining blinks on twitter that don't need large images.
* 4:3 - as mentioned by @irffanasiff , this is a prime candidate for adding more metadata on images for interactions like token launches or NFT mints
* 16:9 - universal image aspect, would work for most embeds
* 1:1 - the current default aspect ratio used on twitter, it has traction and people will continue designing for it
* 1:2 - long images are in high demand so that infographics and more details can be placed above the blink, since customization on other surfaces is limited.

I would suggest that if bounds are needed, bounds of 10:1 and 1:2 are put in place as a starting range and feedback is gathered on what works well over the coming weeks.

Stepping back from this PR, the limitations on render sizes may be more logical at the extension/interstitial/provider level. These boundaries could be parameters, with defaults that could then be overridden by the implementing team based on constraints that exist for their unique situations.

2024-07-17 03:34 UTC, irffanasiff commented
I think in the end it should be a thing that the developer should decide and we as an SDK should be less opiniates about it. if the image is too long then it is the issue of them for using that image and they should worry about it.

2024-07-17 04:33 UTC, zhelezkov commented
> I think in the end it should be a thing that the developer should decide and we as an SDK should be less opiniates about it. if the image is too long then it is the issue of them for using that image and they should worry about it.

the main issue i see is that bad actors with too long image can mess the users twitter feed for example. So I’d recommend adding at least any reasonable limits to prevent it. What @WaggMe says 100% makes sense for me

2024-07-17 09:01 UTC, irffanasiff commented
yep makes sense, adding a max height to it would be great - will do it

2024-07-19 10:19 UTC, zhelezkov commented
hey @irffanasiff, do you still want to address it?
no problem if not, someone from our team could work on it

2024-07-19 11:55 UTC, bhagyamudgal commented
Hey, I have figured out that we can keep `aspect-auto` but set the max height to a number that looks good in X UI, and we should be good. Should I make that change?

For example:

This is the large image 
![image](https://github.com/user-attachments/assets/c7ab0333-9c41-463a-918c-84270155156b)

We fixed the max height to 400px, and it works like this
![image](https://github.com/user-attachments/assets/87f4835f-98ba-43f9-9cd8-20801b87d366)

2024-07-19 13:10 UTC, zhelezkov commented
@bhagyamudgal yeah, let's put some reasonable max height limit for image, that's the decision we all agreed with i think

2024-07-19 16:17 UTC, bhagyamudgal commented
@zhelezkov raised the pr #10 with the changes. Please check and let me know if any more changes are required.

2024-07-22 17:04 UTC, zhelezkov commented
@bhagyamudgal thanks, let's move discussion to #10

2024-07-22 17:04 UTC, closed without merging